[package]
name = "blindbit-lib"
version = "0.1.0"
edition = "2024"

[build-dependencies]
tonic-prost-build = "0.14.2"

[dependencies]
prost = "0.14.1"
prost-types = "0.14.1"
tonic = { version = "0.14.2", features = ["tls-ring", "tls-webpki-roots"] }
tonic-prost = "0.14.2"

