[workspace]
resolver = "3"
members = ["blindbit-cli", "blindbit-lib", "tests"]

[workspace.package]
authors = ["Setor"]

# [profile.release]
# debug = "line-tables-only"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = "debuginfo"
