[package]
name = "blindbit-cli"
version = "0.1.0"
edition = "2024"

# Default binary (main.rs)
[[bin]]
name = "blindbit-cli"
path = "src/main.rs"

[dependencies]
blindbit-lib = { path = "../blindbit-lib" }
