[package]
name = "blindbit-test"
version = "0.1.0"
edition = "2024"

[dependencies]
blindbit-lib = { path = "../blindbit-lib" }
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros"] }
tonic = "0.14.2"
